address: 127.0.0.1
port: 7997
joint_topic: /ur/joint_states
joint_data_items:
    - j1_angle
    - j2_angle
    - j3_angle
    - j4_angle
    - j5_angle
    - j6_angle
gripper_topic: /gripper_status
gripper_data_items: gripper_state
