<?xml version="1.0" ?>
<robot name="NIST_Robot" xmlns:xacro="http://ros.org/wiki/xacro">
	
	<!-- parameters -->
	<xacro:property name="end_effector_length" value="0.35"/>
	<xacro:property name="end_effector_diameter" value="0.1"/>

	<!-- color definitions -->
  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>
  <material name="yellow">
    <color rgba="1 1 0 1"/>
  </material>
  <material name="orange">
    <color rgba="1 0.66 0.48 1"/>
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>
  <material name="light_blue">
    <color rgba="0.78 0.94 0.965 1"/>
  </material>

  <!-- robot definitions, also defined in robot urdf -->
	<link name="tool0"/>
	<!-- link definitions -->
	<!--link name="palm"/-->
	<link name="tcp_frame"/>
	<link name="end_effector_link">
		<visual>
			<origin xyz="0.0 0.0 ${end_effector_length * 0.5}" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="${end_effector_diameter * 0.5}" length="${end_effector_length}"/>
			</geometry>
			<material name="light_blue"/>
		</visual>
	</link>
	
	<!-- joint definitions -->
	<joint name="tool_to_end_effector" type="fixed">
		<origin xyz="0 0 0" rpy="0 1.5708 0"/>
		<parent link="tool0"/>
		<child link="end_effector_link"/>
	</joint>
	<joint name="tool_to_tcp" type="fixed">
		<origin xyz="${end_effector_length} 0 0" rpy="0 0 0"/>
		<parent link="tool0"/>
		<child link="tcp_frame"/>
	</joint>
	
</robot>
